In [19]:
import pandas as pd
import json

In [20]:
df = pd.read_json("dermstore_data.json")

In [21]:
df.shape

(126, 24)

In [29]:
df.describe()

                sku    product_id       price                  scraped_at
count  1.260000e+02  1.260000e+02  126.000000                         126
mean   1.318559e+07  1.318559e+07   78.088333  2024-02-11 11:17:24.230158
min    1.030272e+07  1.030272e+07   11.000000         2024-02-11 11:15:28
25%    1.169451e+07  1.169451e+07   35.000000         2024-02-11 11:16:21
50%    1.291211e+07  1.291211e+07   52.500000         2024-02-11 11:17:18
75%    1.445992e+07  1.445992e+07   97.250000  2024-02-11 11:18:28.750000
max    1.564870e+07  1.564870e+07  495.000000         2024-02-11 11:20:15
std    1.513464e+06  1.513464e+06   77.597091                         NaN

In [30]:
df.head(5)

,url,title,brand,sku,product_id,price,currency,availability,condition,rating_value,...,raw_ingredients,how_to_use,raw_how_to_use,skin_type_and_concerns,raw_skin_type_and_concerns,range,volume,images,uniq_id,scraped_at
0,https://www.dermstore.com/p/exclusive-neostrat...,Exclusive NEOSTRATA Anti-Aging Firming Duo,Neostrata,13441438,13441438,188.0,USD,OutOfStock,NewCondition,,...,"<div aria-labelledby=""Ingredients"" class=""cont...",Gently smooth over neck and décolletage twice ...,"<div aria-labelledby=""How-to-Use"" class=""conte...",,,,80ml,https://static.thcdn.com/productimg/original/1...,6635eafe-d8bd-53c7-b232-d359b208b4a1,2024-02-11 11:15:28
1,https://www.dermstore.com/p/pmd-pmd-clean-1-pi...,PMD Clean (1 piece),PMD,12905594,12905594,79.2,USD,InStock,NewCondition,4.38,...,"<div aria-labelledby=""Ingredients"" class=""cont...",Step 1: Rinse and Apply Cleanser.\n Rinse fac...,"<div aria-labelledby=""How-to-Use"" class=""conte...",Acne: BlackheadsAging Skin: Loss of FirmnessAp...,"<div aria-labelledby=""Skin-Type-&amp;-Concerns...",,,https://static.thcdn.com/productimg/original/1...,7c436149-00ab-56d5-8274-cf24a991dbaf,2024-02-11 11:15:29
2,https://www.dermstore.com/p/neom-focus-the-min...,NEOM Focus the Mind Essential Oil Blend 0.3 fl...,NEOM,12540840,12540840,24.0,USD,InStock,NewCondition,,...,"<div aria-labelledby=""Ingredients"" class=""cont...",To experience the full Feel Good Vibes Essenti...,"<div aria-labelledby=""How-to-Use"" class=""conte...",,,,10ml,https://static.thcdn.com/productimg/original/1...,6c9186b2-c19d-55e5-a45b-c6be55bc74d6,2024-02-11 11:15:33
3,https://www.dermstore.com/p/briogeo-curl-chari...,Briogeo Curl Charisma™ Rice Amino + Avocado Hy...,Briogeo,11271963,11271963,28.0,USD,InStock,NewCondition,4.33,...,"<div aria-labelledby=""Ingredients"" class=""cont...",Apply to wet hair and massage from root to tip...,"<div aria-labelledby=""How-to-Use"" class=""conte...","Application Area: Hair, ScalpIdeal for these C...","<div aria-labelledby=""Skin-Type-&amp;-Concerns...",Curl Charisma,236ml,https://static.thcdn.com/productimg/original/1...,2b54ea9f-b05a-58be-8ef6-37d115ac19a9,2024-02-11 11:15:34
4,https://www.dermstore.com/p/dermalogica-christ...,Dermalogica Retinol Renewal Gift Set ($186 Value),Dermalogica,15508780,15508780,129.0,USD,InStock,NewCondition,,...,"<div aria-labelledby=""Ingredients"" class=""cont...",Super Rich Repair: Apply to face and neck with...,"<div aria-labelledby=""How-to-Use"" class=""conte...",,,,,https://static.thcdn.com/productimg/original/1...,57eafd78-cb46-57fb-9ff1-564f8f47f41d,2024-02-11 11:15:34

In [24]:
df["skin_type_and_concerns"].value_counts()

skin_type_and_concerns
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            73
Acne: BlackheadsAging Skin: Loss of FirmnessApplication Area: FaceIdeal for these Concerns: Acne, Large Pores, OilinessProfessional Tools and Devices: Cleansing DevicesSkin Care: Professional Tools and DevicesSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                                                                                                                                                                                                 1
Application Area: Hair, ScalpIdeal for these Concerns: Damaged Hair, Free Radical Damage, Frizzy HairHair Care: ShampooHair Type: Coarse Hair, Curly Hair, Dry or Damaged HairIngredient: Aloe Vera, Amino Acids, Antioxidants, Shea Butter, Vitamin C, Vitamin EPreferences: Certified Cruelty-Free, Gluten-Free, Natural, Paraben-Free, Sulfate-FreeShampoo: Smoothing Shampoo                                                                                                                                                                                             1
Application Area: HairIdeal for these Concerns: Damaged Hair, Frizzy HairHair Care: ShampooHair Type: Coarse Hair, Color-Treated Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairIngredient: Essential Oils, Herbal Extracts, PanthenolMen: Men's EssentialsMen's Essentials: Men's Hair ProductsPreferences: Certified Cruelty-Free, Certified OrganicShampoo: Repair Shampoo                                                                                                                                                                       1
Application Area: HairColor Family: RedIdeal for these Concerns: Damaged HairHair Care: Hair ColorIngredient: Biotin, Essential Oils, Herbal ExtractsPreferences: Certified Cruelty-Free, Clean, Sulfate-Free, Vegan                                                                                                                                                                                                                                                                                                                                                         1
Aging Skin: Loss of FirmnessApplication Area: Body, Decollete, FaceBath and Body: Lotions and OilsIdeal for these Concerns: Aging Skin, Calluses, Dryness and Dehydration, Psoriasis, Stretch MarksIngredient: Dimethicone, Essential Oils, Olive Oil, Shea ButterLotions and Oils: Body LotionPreferences: Clean, Fragrance-Free, Gluten-Free, VeganSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                                                             1
Application Area: Body, Face, NeckIngredient: Hyaluronic AcidPreferences: CleanSkin Care: Skin Care TreatmentsSkin Care Treatments: Face MasksSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive SkinWellness | Internal Factors: Stress Solutions and Treatments                                                                                                                                                                                                                                                        1
Aging Skin: Fine Lines and Wrinkles, Loss of FirmnessApplication Area: Decollete, FaceConcern: Aging Skin, Free Radical DamageIngredient: Vitamin EPreferences: Fragrance-Free, Paraben-FreeSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                                                                                                                                                                                                                      1
Application Area: EyesColor Family: NudeEye Makeup: EyeshadowEyeshadow: Cream EyeshadowIngredient: Beeswax, Mica, Titanium Dioxide, Vitamin EMakeup: Eye MakeupPreferences: Clean                                                                                                                                                                                                                                                                                                                                                                                            1
Application Area: BodyBath and Body: Bath and ShowerBath and Shower: Body Scrubs and ExfoliatorsIdeal for these Concerns: Free Radical DamageHoliday: Gifts for FriendsIngredient: Aloe Vera, Shea Butter, Vitamin CPreferences: Certified Cruelty-Free, Natural                                                                                                                                                                                                                                                                                                             1
Application Area: FaceCleansers and Exfoliators: Face WashIdeal for these Concerns: Large PoresIngredient: Castor Oil, Panthenol, Salicylic AcidPreferences: Certified Cruelty-Free, Fragrance-Free                                                                                                                                                                                                                                                                                                                                                                          1
Application Area: HairConcern: Frizzy HairHair Care: Styling ToolsHair Type: Coarse Hair, Color-Treated Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairStyling Tools: Hair Brushes and Combs                                                                                                                                                                                                                                                                                                                                                        1
Application Area: FaceCleansers and Exfoliators: Face WashIdeal for these Concerns: Free Radical Damage, Hyperpigmentation, Hypersensitive SkinFeatures: Adaptogenic Skin CareIngredient: Essential Oils, Shea ButterPreferences: Certified Cruelty-Free, Certified Organic, Gluten-Free, Natural, Paraben-Free, Phthalate-Free, Sulfate-Free, VeganSkin Care: Cleansers and ExfoliatorsSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                          1
Application Area: FaceIdeal for these Concerns: RednessFace Sun Care: Face SunscreenIngredient: Aloe Vera, Antioxidants, Vitamin E, Zinc OxidePreferences: Dermatologist Approved, Paraben-FreeSkin Care: Face Sun CareSkin Type: Mature SkinSPF: SPF 30+Wellness | External Factors: UV Ray Protectors and Treatments                                                                                                                                                                                                                                                       1
Application Area: HairHair Care: Hair ColorHair Type: Color-Treated Hair, Normal HairPreferences: Certified Cruelty-Free, Gluten-Free, Paraben-Free, Phthalate-Free, Sulfate-Free, Vegan                                                                                                                                                                                                                                                                                                                                                                                     1
Aging Skin: Fine Lines and WrinklesApplication Area: Decollete, Face, NeckIdeal for these Concerns: Dryness and Dehydration, Free Radical Damage, Hyperpigmentation, Sun DamageIngredient: Antioxidants, Herbal Extracts, Vitamin C, Vitamin EPreferences: Fragrance-Free, Paraben-Free, Phthalate-Free, Sulfate-FreeSkin Care: Skin Care TreatmentsSkin Care Treatments: Face SerumsSkin Type: Combination Skin, Dry Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                                                           1
Application Area: FaceIdeal for these Concerns: Redness, Varicose Veins and Spider VeinsIngredient: Essential OilsPreferences: Certified Cruelty-FreeSkin Care: Skin Care TreatmentsSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                                                                                                                                                                                                                                                              1
Application Area: Hair, ScalpHair Care: Styling ToolsStyling Tools: Hair Brushes and Combs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Aging Skin: Fine Lines and WrinklesApplication Area: Face, NeckIdeal for these Concerns: Dryness and DehydrationFragrance Note: FloralIngredient: Antioxidants, Coenzyme Q10, Essential Oils, Jojoba, Vitamin AMoisturizers: Face OilsPreferences: Certified Cruelty-Free, Gluten-Free, Natural, Paraben-Free, Phthalate-Free, Sulfate-Free, VeganSkin Care: MoisturizersSkin Type: Dry Skin, Mature Skin, Sensitive Skin                                                                                                                                                    1
Application Area: HairIdeal for these Concerns: Free Radical DamageHair Care: ShampooHair Type: Curly HairIngredient: Antioxidants, Vitamin CPreferences: Paraben-FreeShampoo: Volume Shampoo                                                                                                                                                                                                                                                                                                                                                                                1
Application Area: Eyebrows, FaceMakeup: Cosmetic ToolsPreferences: Certified Cruelty-Free                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Application Area: HairIdeal for these Concerns: Frizzy Hair, Hypersensitive SkinConditioner: Smoothing ConditionerHair Care: ConditionerHair Type: Coarse Hair, Color-Treated Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairIngredient: DimethiconePreferences: Fragrance-Free, Paraben-Free, Sulfate-Free                                                                                                                                                                                                                                         1
Application Area: HairIdeal for these Concerns: Damaged Hair, Dryness and Dehydration, Free Radical Damage, Sun DamageHair Care: ShampooHair Type: Coarse Hair, Color-Treated Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairIngredient: Algae Extract, Glycolic Acid, Herbal Extracts, Lactic Acid, Malic Acid, Niacinamide, PanthenolPreferences: Paraben-Free, Sulfate-FreeShampoo: Color ShampooSkin Type: Acne-Prone Skin, Combination Skin, Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive Skin                                     1
Aging Skin: Fine Lines and WrinklesApplication Area: Cheeks, Face, Lips, Neck, ScalpIdeal for these Concerns: SunburnFinish: MatteIngredient: Dimethicone, Titanium Dioxide, Zinc OxidePreferences: Oil-FreeSkin Type: Dry Skin, Mature Skin, Normal Skin, Oily Skin, Sensitive SkinSPF: SPF 30+                                                                                                                                                                                                                                                                             1
Application Area: HairHair Care: Styling ToolsHair Type: Coarse Hair, Color-Treated Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairStyling Tools: Flat Iron                                                                                                                                                                                                                                                                                                                                                                                         1
Application Area: EyesIdeal for these Concerns: Dark Circles, PuffinessEye Care: Eye Treatments and SerumsIngredient: Algae Extract, Castor Oil, Essential Oils, Hyaluronic Acid, Jojoba, NiacinamidePreferences: Certified Cruelty-Free, Clean, Dermatologist Approved, Gluten-Free, Paraben-Free, Phthalate-Free, Sulfate-Free, VeganSkin Care: Eye CareWellness | Internal Factors: Stress Solutions and Treatments                                                                                                                                                       1
Application Area: HairIdeal for these Concerns: OilinessFragrance Note: CitrusHair Care: ShampooHair Type: Coarse Hair, Curly Hair, Dry or Damaged Hair, Fine Hair, Normal Hair, Oily HairIngredient: Antioxidants, KeratinPreferences: Certified Cruelty-Free, Gluten-Free, Paraben-Free, Phthalate-Free, Sulfate-FreeShampoo: Dry Shampoo                                                                                                                                                                                                                                  1
Bath and Body: Bath and ShowerBath and Shower: Bath TreatmentIngredient: Essential OilsPreferences: Certified Cruelty-Free, NaturalWellness | Internal Factors: Sleep Deprivation Defenders and Treatments                                                                                                                                                                                                                                                                                                                                                                   1
Aging Skin: Fine Lines and WrinklesApplication Area: FaceIdeal for these Concerns: Large PoresProfessional Tools and Devices: Anti-Aging Tools and DevicesSkin Care: Professional Tools and DevicesSkin Type: Mature Skin                                                                                                                                                                                                                                                                                                                                                    1
Application Area: Body, Cheeks, Decollete, Face, Feet, Hands, NeckIdeal for these Concerns: Dryness and Dehydration, RednessIngredient: Antioxidants, Ceramides, Hyaluronic Acid, Panthenol, Titanium Dioxide, Vitamin AMoisturizers: Face MoisturizerSkin Care: MoisturizersSkin Type: Dry Skin, Mature Skin, Normal Skin, Sensitive Skin                                                                                                                                                                                                                                   1
Application Area: Face, NeckIdeal for these Concerns: Dryness and Dehydration, Redness, RosaceaIngredient: Dimethicone, Vitamin EMoisturizers: Face MoisturizerSkin Care: MoisturizersSkin Type: Acne-Prone Skin, Oily Skin, Sensitive Skin                                                                                                                                                                                                                                                                                                                                  1
Application Area: Eyes, FaceCoverage: FullFace Makeup: Face ConcealerFinish: SatinIngredient: Aloe Vera, Dimethicone, Essential Oils, Jojoba, Mica, Shea Butter, Titanium DioxideMakeup: Face MakeupPreferences: Clean, Oil-Free                                                                                                                                                                                                                                                                                                                                             1
Application Area: FaceIdeal for these Concerns: Aging Skin, Free Radical DamageIngredient: Aloe Vera, Antioxidants, Essential Oils, Green Tea, Shea Butter, Vitamin EPreferences: Certified Cruelty-Free, NaturalSkin Care: Skin Care Kits and Value Sets                                                                                                                                                                                                                                                                                                                    1
Application Area: Teeth and MouthIngredient: Titanium DioxideOral Care: Teeth Whitening, ToothpastePreferences: Clean                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Aging Skin: Fine Lines and Wrinkles, Lip Lines Application Area: LipsIdeal for these Concerns: Chapped LipsIngredient: Coconut Oil, Shea ButterLip Makeup: Lip Balms TreatmentsMakeup: Lip MakeupPreferences: Certified Organic                                                                                                                                                                                                                                                                                                                                              1

In [25]:
df.shape

(126, 24)

In [26]:
df["category"]

0      Brands / NEOSTRATA / Exclusive NEOSTRATA Anti-...
1                     Brands / PMD / PMD Clean (1 piece)
2      Brands / NEOM / NEOM Focus the Mind Essential ...
3      Brands / Briogeo / Briogeo Curl Charisma™ Rice...
4      Brands / Dermalogica / Dermalogica Retinol Ren...
                             ...
121    Brands / RMS Beauty / RMS Beauty Kakadu Beauty...
122    Brands / Tarte Cosmetics / Tarte Foundcealer F...
123    Brands / Erborian / Erborian Skin Therapy Mult...
124    Brands / This Works / this works Perfect Hands...
125    Brands / KYPRIS / KYPRIS Clearing Serum Balanc...
Name: category, Length: 126, dtype: str

In [ ]:
# on supprime les colonnes qui ne serviront pas au modèle : sku, availability, uniq_id, scraped_at
df =